name: CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main", "develop" ]

jobs:
    lint-check:

        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

            -   name: KtLint Check
                run: ./gradlew ktlintCheck

            -   name: Detekt Check
                run: ./gradlew detekt

    run-tests:

        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

            -   name: Run Unit Tests
                run: ./gradlew test

            -   name: Run Integration Tests
                run: ./gradlew integrationTest

    dependency-submission:

        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'

            # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
            # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
            -   name: Generate and submit dependency graph
                uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
